// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipe.Models;

namespace Recipe.Migrations
{
    [DbContext(typeof(recipesContext))]
    [Migration("20201118113251_StepNumberAdded")]
    partial class StepNumberAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Recipe.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("IngredientAmount")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IngredientName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("RecipeTableId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId")
                        .HasName("PK__Ingredie__BEAEB25AF59F733E");

                    b.HasIndex("RecipeTableId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Recipe.Models.RecipeTable", b =>
                {
                    b.Property<int>("RecipeTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("RecipeDescription")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RecipeName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RecipeTableId")
                        .HasName("PK__Recipes__FDD988B02F32FFD7");

                    b.HasIndex("UserId");

                    b.ToTable("RecipeTables");
                });

            modelBuilder.Entity("Recipe.Models.Step", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("RecipeTableId")
                        .HasColumnType("int");

                    b.Property<string>("StepDescription")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("StepId")
                        .HasName("PK__Steps__2434335752018F14");

                    b.HasIndex("RecipeTableId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("Recipe.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CB50B52E6");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Recipe.Models.Ingredient", b =>
                {
                    b.HasOne("Recipe.Models.RecipeTable", "RecipeTable")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeTableId")
                        .HasConstraintName("FK__Ingredien__Recip__286302EC");

                    b.Navigation("RecipeTable");
                });

            modelBuilder.Entity("Recipe.Models.RecipeTable", b =>
                {
                    b.HasOne("Recipe.Models.User", "User")
                        .WithMany("RecipeTables")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Recipes__UserId__25869641")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recipe.Models.Step", b =>
                {
                    b.HasOne("Recipe.Models.RecipeTable", "RecipeTable")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeTableId")
                        .HasConstraintName("FK__Steps__RecipeId__2B3F6F97");

                    b.Navigation("RecipeTable");
                });

            modelBuilder.Entity("Recipe.Models.RecipeTable", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Recipe.Models.User", b =>
                {
                    b.Navigation("RecipeTables");
                });
#pragma warning restore 612, 618
        }
    }
}
